### ISSUE TITLE
Circumvent the limitations of this implementation

### ISSUE THREAD

**Issue by rnjailamba** [awslabs/cognito-user-profiles-export-reference-architecture#11]
**Is your feature request related to a problem? Please describe.**
How can we make this solution truly seamless i.e. by exporting sensitive information ex. Passwords as well.

**Describe the feature you'd like**
We would like to export sensitive information ex. Passwords to make the solution multi-region

**Additional context**
All the limitations are listed here - https://docs.aws.amazon.com/solutions/latest/cognito-user-profiles-export-reference-architecture/solution-components.html#limitations

**Comment by ericquinones** [comment]
Hello - thanks for the feedback.

This solution uses the Cognito APIs to retrieve the user profile information, which is then exported to the DynamoDB Global Table. Passwords are not exposed by the API at all so it is not possible to export them.

**Comment by rnjailamba** [comment]
Understood, thanks for the update.
