### ISSUE TITLE
GlobalTableCheckerRole Policy Document causing cfn-template to fail

### ISSUE THREAD

**Issue by gmedard** [awslabs/cognito-user-profiles-export-reference-architecture#2]
Tried the One-Click deployment on the AWS-Solutions site using the default region (us-east-1) and I'm receiving the following error:

- The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; Proxy: null)

- The following resource(s) failed to create: [GlobalTableCheckerRole]. Rollback requested by user.

**Comment by ericquinones** [comment]
Hi @gmedard -

Thanks for raising this. I was able to reproduce this by using an invalid value as the Secondary Region when deploying the stack. For instance, I used `us-west--2`. Can you please try again and see if maybe there was a typo you used when setting that parameter?

We'll also look into tightening the regex that validates that parameter.

**Comment by gmedard** [comment]
Thanks @ericquinones  - There was an extra character being copied when I was pasting.  That fixed that issue.
