### ISSUE TITLE
Error during NotificationTopic creation due to Topic's displayName exceeding 100 chars.

### ISSUE THREAD

**Issue by Gireeshjobz** [awslabs/cognito-user-profiles-export-reference-architecture#7]
This solution is setting a very long name for the displayName attribute of SNS CreateTopic request. The displayName has a constraint - 100 max char length.

> TopicName: !Sub "cognito-user-profiles-export-reference-architecture-${AWS::Region}-${StackSetConstantsCustomResource.SolutionInstanceUUID}"

> Error:
"Summaries": 
      "Status": "FAILED",
      "StatusReason": "ResourceLogicalId:NotificationTopic, ResourceType:AWS::SNS::Topic, ResourceStatusReason:Invalid parameter: Attributes Reason: DisplayName (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: fd64f631-1460-5c61-bdf8-ae4548db41f7; Proxy: null).

Is it possible to cut down on the topic name hardcoded string ?

**Comment by ericquinones** [comment]
Hi @Gireeshjobz - Thanks for reporting this. We will look into shortening the topic names for the next release.

Do you mind sharing how you deployed the solution (i.e. using the AWS CLI or CloudFormation consonle) and what regions you used as primary and secondary? 

I deployed using ap-northeast-1 / ap-southeast-1 as primary / secondary and while I do see that the resulting topic names are long & above 100 characters, I didn't get an error during deployment.

**Comment by Gireeshjobz** [comment]
Hi @ericquinones - 

>I deployed using ap-northeast-1 / ap-southeast-1 as primary / secondary and while I do see that the resulting topic names are long & above 100 characters, I didn't get an error during deployment.

The property that its failing on is DisplayName (max 100 chars). The Topic Name can be max 256 chars.
Below is the screenshot of createTopic console.
![Screen Shot 2021-01-11 at 10 52 09 AM](https://user-images.githubusercontent.com/38195185/104225424-3968d380-53fb-11eb-99e2-486dfc179741.png)

**Comment by tomnight** [comment]
Fixed in version 1.0.1
